sudo: false
language: php
matrix:
  include:
  - php: 5.5
    env: WP_TRAVISCI=travis:js
before_install:
  - echo "Travis before_install logic disabled for testing Travis quickly"
  - |
    if [[ "$WP_TRAVISCI_CUSTOM_BEFORE_INSTALL_SRC" ]]; then
      echo "Running custom BEFORE_INSTALL from $WP_TRAVISCI_CUSTOM_BEFORE_INSTALL_SRC"
      wget -O /tmp/custom-before-install.sh "$WP_TRAVISCI_CUSTOM_BEFORE_INSTALL_SRC?cachebust=$(date "+%Y%m%dT%H%M%S")";
      source /tmp/custom-before-install.sh;
    fi
before_script:
  - echo "Travis before_script logic disabled for testing Travis quickly"
  - |
    if [[ "$WP_TRAVISCI_CUSTOM_BEFORE_SCRIPT_SRC" ]]; then
      echo "Running custom BEFORE_SCRIPT from $WP_TRAVISCI_CUSTOM_BEFORE_SCRIPT_SRC"
      wget -O /tmp/custom-before-script.sh "$WP_TRAVISCI_CUSTOM_BEFORE_SCRIPT_SRC?cachebust=$(date "+%Y%m%dT%H%M%S")";
      source /tmp/custom-before-script.sh;
    fi
script:
  - echo "Travis script logic disabled for testing Travis quickly"
  - |
    if [[ "$WP_TRAVISCI_CUSTOM_SCRIPT_SRC" ]]; then
      echo "Running custom after_script from $WP_TRAVISCI_CUSTOM_SCRIPT_SRC"
      wget -O /tmp/custom-script.sh "$WP_TRAVISCI_CUSTOM_SCRIPT_SRC?cachebust=$(date "+%Y%m%dT%H%M%S")";
      source /tmp/custom-script.sh;
    fi
after_script:
  - |
    if [[ "$WP_TRAVISCI_CUSTOM_AFTER_SCRIPT_SRC" ]]; then
      echo "Running custom after_script from $WP_TRAVISCI_CUSTOM_AFTER_SCRIPT_SRC"
      wget -O /tmp/custom-after-script.sh "$WP_TRAVISCI_CUSTOM_AFTER_SCRIPT_SRC?cachebust=$(date "+%Y%m%dT%H%M%S")";
      source /tmp/custom-after-script.sh;
    fi
notifications:
  slack:
    rooms:
      secure: WuMCpfgrm0GIdPbYzsGOsakZ5x7QIbEBwD+CPHVXGKbL3ZbqQ+BVcDRnMiwzxjgf1vzg2de0taXCSMGKBxsWce23NZkOnmwPdIB8XOnwDV7T7zylgYD5S7p3gI6gV0l8Y3/gROdXFZap6viC1qRr4E79ow53RKk7E3WyOo7TWqo=
    on_start: never
    on_failure: always
    on_success: change
